### ISSUE TITLE
COVID sna

### ISSUE THREAD

**Issue by genghiskhanofnz** [briatte/awesome-network-analysis#102]
Hi there, I have discovered some published papers using sna on pandemic.  Datasets or tutorials or other resources are necessary to this list.  That would be very helpful for medical and public health researchers on this very important 'contact tracing' work to improve pandemic containment.  Thank you.

**Comment by briatte** [comment]
Hi @genghiskhanofnz -- Yes, I noticed the same thing: during the pandemic, there was of course a huge interest in how infectious disease epidemiology and related disciplines handle contamination, contact tracing etc. -- largely via network methods.

However, I sadly do not have the time to do personal research to document that in the list. Suggestions and PRs are very welcome, though!
