### ISSUE TITLE
Broken Link: Social Network Analysis Group at Stanford

### ISSUE THREAD

**Issue by cllei12** [briatte/awesome-network-analysis#118]
The link for the "Social Network Analysis Group at Stanford" seems broken.

Is it Jure Leskovec's research group? If so, the link should be https://snap.stanford.edu/index.html

Thanks for maintaining such an amazing repo!

**Comment by briatte** [comment]
Hi @cllei12 -- I guess the link was to SNAP, indeed. A similar link is in the 'data' section. I have updated both. Thanks!
