### ISSUE TITLE
Add more awesome two-mode / hypernetwork stuff

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#14]
* [x] Two-mode subsection.
* [ ] Hypernetworks subsection?

**Comment by taniki** [comment]
- Are two-mode subsection equivalent to bi-partite networks?
- Are hypernetworks also equivalent to multiplex networks? This is a big topic in the complex system approach of networks since few years

**Comment by briatte** [comment]
> Are two-mode subsection equivalent to bi-partite networks?

Two-mode = Bipartite, yes. Don't know about "subsection" in the context of graphs.

> Are hypernetworks also equivalent to multiplex networks?

As far as I understand, yes, but I know very little about them. Hypernetworks are also called k-partite in some contexts, as far as I understand.

**Comment by taniki** [comment]
Last time I mentioned a multiplex network, somone send me this reference http://www.springer.com/us/book/9783319067926 did not got time to dig into it until then.

Schreiber, Falk, Andreas Kerren, Katy Börner, Hans Hagen, and Dirk Zeckzer. 2014. "Heterogeneous Networks on Multiple Levels". Information Visualization - Towards Multivariate Network Visualization (Dagstuhl Seminar 13201). Springer Verlag.

**Comment by briatte** [comment]
There's good stuff also from a Japanese guy that I have somewhere on disk. I'll start the subsection when I have at least 4-5 links.

**Comment by taniki** [comment]
Akera, A. 2007. “Constructing a Representation for an Ecology of Knowledge: Methodological Advances in the Integration of Knowledge and Its Various Contexts.” Social Studies of Science 37(3):413–41.

**Comment by briatte** [comment]
Nah — I know awesome lists should be tolerant, but I'm almost literally allergic to ANT…

**Comment by taniki** [comment]
I will be curious about your reference then (:

I am also trying to find a reference that is not too deep into a geospatial framework

**Comment by briatte** [comment]
Found it – Liu and Murata, "[Detecting Communities in K-partite K-uniform (Hyper) Networks](http://link.springer.com/article/10.1007/s11390-011-0177-0?no-access=true)", 2011.

See also [2010 conference paper](https://www.researchgate.net/publication/221023086_Detecting_communities_from_tripartite_networks).

See also [2009 working paper by different authors](http://snap.stanford.edu/nipsgraphs2009/papers/neubauer-paper.pdf).

Problem – knowledge of hypergraphs seems less 'stabilised' than for other graphs. In general, it seems to me, network analysis is still quite experimental / shy about exploring k-partite graphs when _k_ > 1.

**Comment by briatte** [comment]
Okay, for now I'm just gonna add the Murata Lab to the list of non-US research groups. Perhaps we'll come back to bi/tri/k-partite networks later on.
