### ISSUE TITLE
Add more comments to qualify awesomeness

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#21]
Requested by the author of the Awesome Manifesto.

**Comment by mmosleh** [comment]
Great list of resources. At the first glance I think the following can be added:

-"Dissemination":
Connected: The Surprising Power of Our Social Networks and How They Shape Our Lives -- How Your Friends' Friends' Friends Affect Everything You Feel, Think, and Do by Nicholas A. Christakis  (Author), James H. Fowler  (Author)

- "Journals":
IEEE Transactions on Network Science and Engineering

**Comment by briatte** [comment]
Thanks @mmosleh 

I would like to add you to the contributors at the bottom of the page. Would you mind giving me your full name and a link to your academic page or other profile, if you have one?

**Comment by mmosleh** [comment]
Sure,

Mohsen Mosleh (mmosleh@stevens.edu), 
Ph.D. Candidate, School of Systems and Enterprises
Research Assistant, Complex Evolving Networked Systems Lab
Stevens Institute of Technology, Hoboken, NJ

Personal academic website: http://personal.stevens.edu/~mmosleh
Our research group website: http://web.stevens.edu/cens/

Thanks

**Comment by briatte** [comment]
Brilliant, thank you very much!

**Comment by briatte** [comment]
Coming back to it after a few years, the list is fairly well-commented, and the resources mentioned above have been added. Closing.
