### ISSUE TITLE
ANN or CANA?

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#39]
A question for @gvegayon, perhaps:

Are these groups the same [USC](https://www.usc.edu/)-based group? If so, which URL is the correct (still updated) one?
- [Center for Applied Network Analysis (CANA)](https://usccana.github.io/) – _currently not listed_
- [Annenberg Networks Network (ANN)](http://uscann.tumblr.com/) – _currently listed_

**Comment by gvegayon** [comment]
Both at USC, different schools. CANA is at the school of medicine, which I'm part of, and the right URL is http://cana.usc.edu. Not familiar with ANN so I wouldn't be able to tell if the group is either active or the URL is the right one.

**Comment by briatte** [comment]
Okay, thanks @gvegayon -- I'll add CANA separately then.
