### ISSUE TITLE
Invite awesome GitHub users to awesomely contribute

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#4]
* [x] @gaborcsardi
* [x] @kateto
* [ ] @jdwilson4
* [x] @matthewjdenny
* [ ] @pedroj
* [x] @tpoisot

**Comment by tpoisot** [comment]
:+1: let me see what I have

**Comment by briatte** [comment]
Damn, how could I forget

- [x] @gaborcsardi

(Although I did already include pretty much everything igraph-related I could find.)

**Comment by briatte** [comment]
__Dear awesome contributors__ – please feel free to submit your own list of awesome contributors. Let's snowball sample from there on!
