### ISSUE TITLE
Network analysis courses

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#40]

**Comment by imRP26** [comment]
I found a few more university courses. They're quite good as well.

- http://www-personal.umich.edu/~mejn/courses/2015/cscs535/index.html

- https://www.cs.purdue.edu/homes/neville/courses/ST598T.html

- https://sites.google.com/a/yale.edu/462-562-graphs-and-networks/

- http://www.cs.yale.edu/homes/spielman/561/

- http://web.stanford.edu/~jugander/mse334/

**Comment by briatte** [comment]
I've also enjoyed that one, although the lectures do not seem to keep going online: http://tuvalu.santafe.edu/~aaronc/courses/3352/

I think I need help selecting among those courses. Are the links always to the most recent version of each course?

**Comment by briatte** [comment]
@rahul-38-26-0111-0003 Going through your list many years later:

- http://www-personal.umich.edu/~mejn/courses/2015/cscs535/index.html

This one has no lecture notes. I managed to access the [2017 edition](http://www-personal.umich.edu/~mejn/courses/2017/cscs535/index.html), which has the same issue. More recent editions are sadly locked in Canvas. It's a shame, because the author is such a giant in the field!

- https://www.cs.purdue.edu/homes/neville/courses/ST598T.html

Links is dead, and the author's faculty page has [more dead links](https://www.cerias.purdue.edu/site/people/faculty/view/967) pointing to what must have been her personal Web space there.

- https://sites.google.com/a/yale.edu/462-562-graphs-and-networks/

Added.

- http://www.cs.yale.edu/homes/spielman/561/

That's a bit too focused for the list, I believe.

- http://web.stanford.edu/~jugander/mse334/

This one is still running, but the focus ('Topics in Social Data') is larger than just networks in my view.

… but thanks! Adding you to the credits.

Also updated a link to another of Aaron Clauset's course. Closing this issue, but reopening a new one to massively update the "Courses" section.
