### ISSUE TITLE
Improve the selection of Julia packages

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#42]
I'm using http://pkg.julialang.org/ but have no clue about the relevance of some of the packages that I have included or excluded. Perhaps @tpoisot might be able to help?

Packages that are [already in the list](https://github.com/briatte/awesome-network-analysis#julia) (all relevant?):

- https://github.com/weijianzhang/EvolvingGraphs.jl
- https://github.com/JuliaLang/Graphs.jl
- https://github.com/JuliaGraphs
  - https://github.com/JuliaGraphs/GraphVisualize.jl
  - https://github.com/JuliaGraphs/LightGraphs.jl
  - https://github.com/JuliaGraphs/Networks.jl
  - https://github.com/JuliaGraphs/GraphCentrality.jl

Potential candidates for inclusion on first inspection:

- [x] https://github.com/PoisotLab/EcologicalNetwork.jl
- [x] https://github.com/nassarhuda/MatrixNetworks.jl
- [x] https://github.com/Azzaare/NetworkFlows.jl
- [x] Add to JuliaGraphs item:
  - [x] https://github.com/JuliaGraphs/NetworkLayout.jl
  - [x] https://github.com/JuliaGraphs/LightGraphsExtras.jl
- [x] https://github.com/abhijithanilkumar/NetworkViz.jl ([video presentation by the author](https://www.youtube.com/watch?list=PLP8iPy9hna6SQPwZUDtAM59-wPzCPyD_S&v=kY5te9NwXo8))
- [x] https://github.com/crsl4/PhyloNetworks.jl
- [x] https://github.com/sisl/BayesNets.jl and https://github.com/sisl/Smile.jl
- [x] https://github.com/sisl/TikzGraphs.jl

Excluded on first inspection:

- https://github.com/johnmyleswhite/HopfieldNets.jl (see note)
- https://github.com/kersulis/MatpowerCases.jl
- https://github.com/AStupidBear/SpikingNetworks.jl (neural networks, see note)

Note: the list does not cover much psy/cog stuff, but perhaps it should. Same goes for neural networks.

**Comment by briatte** [comment]
Let's ping a few more Julia people for diversity and suggestions:

- @nassarhuda 
- @Azzaare
- @abhijithanilkumar (congratulations on your JuliaCon presentation, very informative)
- @crsl4
- @tawheeler from [SISL](https://github.com/sisl)

**Comment by briatte** [comment]
… And let's add @johnmyleswhite, who might be able to determine whether his package fits in the list or not.

**Comment by tawheeler** [comment]
You may want to consider [TikzGraphs](https://github.com/sisl/TikzGraphs.jl).

**Comment by briatte** [comment]
Will do, thanks!

**Comment by briatte** [comment]
Added all candidates, hope this makes sense. Closing for now.
