### ISSUE TITLE
Add an awesome example use of the 'Misérables' character co-occurrence network

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#5]
Subsection: Varia/__Fictional Characters__.

**Comment by taniki** [comment]
example using python/bokeh and some undercover javascript: http://bokeh.pydata.org/en/latest/docs/gallery/les_mis.html

**Comment by briatte** [comment]
__Coool__, that _could_ be the example I need to close #5 (not a graph per se, but close enough)!

**Comment by briatte** [comment]
Link added to the Fictional Characters subsection.
