### ISSUE TITLE
Add Hetionet

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#63]
https://github.com/dhimmel/hetionet

by @dhimmel et al.

**Comment by dhimmel** [comment]
Hey thanks for noticing our network. FYI the official capitalization is Hetionet. In addition to the GitHub, the link to the Neo4j Browser may be of interest: https://neo4j.het.io.

Let me know if you have any questions.

**Comment by briatte** [comment]
Fixed. Will add :)
