### ISSUE TITLE
Add R - tidygraph 

### ISSUE THREAD

**Issue by sandravizmad** [briatte/awesome-network-analysis#67]
https://www.data-imaginist.com/2017/introducing-tidygraph/ 
https://github.com/thomasp85/tidygraph
https://www.rstudio.com/resources/videos/tidying-up-your-network-analysis-with-tidygraph-and-ggraph/

worth adding.

**Comment by briatte** [comment]
Thanks! I added `ggraph` very early and forgot to add the later stuff.

I've listed you as "Sandra B." (with a link to your GitHub profile) in the authors -- please feel free to post your full name if you want it mentioned.
