### ISSUE TITLE
Add netrankr, graphlayouts, levelnet

### ISSUE THREAD

**Issue by briatte** [briatte/awesome-network-analysis#73]
R packages by @schochastics

* https://github.com/schochastics/graphlayouts (placement)
* https://github.com/schochastics/levelnet (bipartite)
* https://github.com/schochastics/netrankr
  * http://blog.schochastics.net/post/network-centrality-in-r-introduction/
  * http://blog.schochastics.net/post/network-centrality-in-r-neighborhood-inclusion/
  * http://blog.schochastics.net/post/network-centrality-in-r-new-ways-of-measuring-centrality/

**Comment by briatte** [comment]
Done.

Dear @schochastics ~ it'd be great if you could document the relationship between the `bipartite` R package and yours. AFAICT, they do not overlap at all, and your package does not accept data from the `bipartite` package (?).

Also, kudos for the great state-of-the-art on graph centrality!

**Comment by schochastics** [comment]
Thanks! Need to look a bit closer at the `bipartite` package. Havent used it yet. My package is going to mostly focus on one-mode projections. But it might also evolve into something more. It is in a very early stage atm. So far, it only accepts igraph objects as graphs.

**Comment by briatte** [comment]
No problem. Haven't used `bipartite` myself either, but it seems to have traction in ecological network analysis, so might be good to keep it in mind.
