### ISSUE TITLE
Add conferences/journals

### ISSUE THREAD

**Issue by vlabatut** [briatte/awesome-network-analysis#75]
Possibly missing conference/journals:

ICWSM: International AAAI Conference on Web and Social Media https://www.icwsm.org/2019/index.php

International Journal of Social Network Mining (IJSNM): http://www.inderscience.com/jhome.php?jcode=ijsnm

IEEE Transactions on Computational Social Systems (TCSS): http://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6570650

International Journal of Network Science (IJNS): http://www.inderscience.com/jhome.php?jcode=ijns

Online Social Networks and Media: https://www.journals.elsevier.com/online-social-networks-and-media/ 

ACM Transactions on Social Computing: https://tsc.acm.org

**Comment by briatte** [comment]
Hi @vlabatut 

Thanks for that. Some firsthand comments below, which I feel somewhat uneasy about, but that's my best assessment so far:

> [ICWSM: International AAAI Conference on Web and Social Media](https://www.icwsm.org/2019/index.php)
> [IEEE Transactions on Computational Social Systems (TCSS)](http://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6570650)
> [ACM Transactions on Social Computing](https://tsc.acm.org)

Are those 95% network analysis? I built the initial list under a similar criterion and want to maintain it.

> [International Journal of Social Network Mining (IJSNM)](http://www.inderscience.com/jhome.php?jcode=ijsnm)
> [International Journal of Network Science (IJNS)](http://www.inderscience.com/jhome.php?jcode=ijns)

I'm unfamiliar with the publisher, which seems to be legit but low-rank.

> [Online Social Networks and Media](https://www.journals.elsevier.com/online-social-networks-and-media/)

Will add, despite [hating Elsevier](http://thecostofknowledge.com/).

**Comment by vlabatut** [comment]
Hi @briatte 

ICWSM mainly focuses on social media: the presented works are not necessarily all using network-based approaches. I'd say it is below 95% network analysis, but quite high though. On the contrary, I'd say that TCSS and ACM TSC contain a number of network-based works, but not close to your criterion.

For the Inderscience journals, you're exactly right. To my opinion, there is quite some variance in the quality of the articles they publish, but some of them are good.

Regarding Elsevieer... I agree completely. I just indicated this journal for the sake of completeness.

Best,
Vincent

**Comment by briatte** [comment]
Alright, added Elsevier's _OSNM_ (last item above). @vlabatut ~ I'm adding you to the final credits, and am taking the liberty to add a link to [your HAL CV](https://cv.archives-ouvertes.fr/vlabatut). Please let me know if you prefer me to have another (ideally noncommercial, like HAL) link instead.

**Comment by vlabatut** [comment]
HAL is fine, thanks!

**Comment by briatte** [comment]
Thanks for your reply, @vlabatut.

I think I'll keep it at this for now, let's see if any of the non-included titles pop up again in suggestions, and I'll reconsider.

Thanks again!
