### ISSUE TITLE
Update Journal of Social Structure link

### ISSUE THREAD

**Issue by atraxler** [briatte/awesome-network-analysis#88]
The linked JoSS page goes to an older version of the site, with the last indexed volume being in 2017. A newer link (from the INSNA website) is: https://www.exeley.com/journal/journal_of_social_structure

That said, the newer site only indexes back to volume 10 (2009), and doesn't point back to the page that has the older archives. So it might be ideal to give both links for this journal?

**Comment by briatte** [comment]
Thanks!
