### ISSUE TITLE
Include NNGT in Python tools?

### ISSUE THREAD

**Issue by Silmathoron** [briatte/awesome-network-analysis#94]
Hi there, this is a bit of a shameless self-advertising, but I just stumbled upon this list and thought I might as well signal my own contribution, in case it might interest some people.

[NNGT](https://github.com/Silmathoron/NNGT) is a unified interface for graph analysis in Python:
* wraps networkx, igraph, and graph-tool libraries
* provides some backup tools using scipy-sparse if no other backend is available
* [normalizes several standard graph measures](https://nngt.readthedocs.io/en/stable/user/graph-analysis.html) so the results are consistent regardless of the backend used
* neuroscientific additions (neuronal populations, interface with [NEST](https://github.com/nest/nest-simulator) and [DeNSE](https://github.com/SENeC-Initiative/DeNSE))

Documentation is available [here](https://nngt.readthedocs.io/en/stable/index.html).

I'm the only developer and there have been few users so far, so there may still be many bugs hidden here and there, but I've been cleaning it up over the years, it's at least usable and documented ;)

I'd rather other people decide whether it's awesome enough, rather than making a PR directly.
That being said, I can make the PR later if it's deemed worthy enough.

**Comment by briatte** [comment]
Hi @Silmathoron 

> I can make the PR later if it's deemed worthy enough.

Please do! And sorry for replying so late.

**Comment by briatte** [comment]
Hi @Silmathoron and @tfardet -- just added the library very sorry for the huge delay.
